name: "ЁЯУе Backlog Task"
description: "ржнржмрж┐рж╖рзНржпрждрзЗрж░ ржЬржирзНржп ржЯрж╛рж╕рзНржХ ржпрзЛржЧ ржХрж░рзБржи"
title: "### Backlog] "
labels: ["Backlog"]
body:
  - type: textarea
    attributes:
      label: ржХрж╛ржЬрзЗрж░ ржмрж┐ржмрж░ржг
      description: ржХрзА ржХрж░рждрзЗ рж╣ржмрзЗ рж▓рж┐ржЦрзБржи
      placeholder: ржпрзЗржоржи тАФ Firebase config setup