.github/ISSUE_TEMPLATE/done.yml

name: "ЁЯПБ Done Task"
description: "ржпрзЗ ржХрж╛ржЬ рж╕ржорзНржкржирзНржи рж╣рзЯрзЗржЫрзЗ"
title: "[Done] "
labels: ["Done"]
body:
  - type: textarea
    attributes:
      label: рж╕ржорзНржкржирзНржи ржХрж╛ржЬрзЗрж░ ржмрж┐ржмрж░ржг
      description: ржХрзА ржХрзА рж╢рзЗрж╖ рж╣рж▓рзЛ рж▓рж┐ржЦрзБржи
      placeholder: ржпрзЗржоржи тАФ Firebase Auth рж╕ржорзНржкржирзНржи

